server:
  port: 9999

spring:
  application:
    name: dispatcher

  cloud:
    nacos:
      discovery:
        server-addr: 1.15.95.83:8848

    gateway:
      routes:
        - id: builtin-aggregation
          uri: lb://builtin-aggregation
          predicates:
            - Path=/aggregation/v1/**

#        - id: builtin-database
#          uri: lb://builtin-database